name: Unit Testing

on:
  pull_request

jobs:
  unit-test:
    name: Unit Testing
    runs-on: ubuntu-latest
    container:
      image: atk4/image:latest # https://github.com/atk4/image
    strategy:
      matrix:
        php: ['7.2', '7.3']
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          DB_DATABASE: db
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
      # Behat
      behat:
        hostname: behat
        image: docksal/behat
        volumes:
          - .:/src
        # Run a built-in web server for access to HTML reports
        ports:
          - 8000:8000
          - 4444:4444
        entrypoint: "php -S 0.0.0.0:8000"
      # Selenium
      browser:
        hostname: browser
        image: selenium/standalone-chrome
        #image: selenium/standalone-firefox
    steps:
      - name: Setup composer
        run: composer install

      - name: Install dependencies and SQL
        run: |
          #mysql -uroot -ppassword -h mysql -e 'CREATE DATABASE atk4;'
          #mysql -uroot -ppassword -h mysql atk4 < demos/atk4.sql
          #mv demos/db.github.php demos/db.php

      - name: Setup coverage / build folders
        run: |
          mkdir -p coverage
          mkdir -p build

      - name: Unit Testing
        run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - name: Run behat test
        run: docker exec behat vendor\bin\behat

      - name: Merge coverage logs
        run: vendor/bin/phpcov merge build/logs/ --clover build/logs/cc.xml;

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: build/logs/cc.xml
