name: Unit Testing

on:
  pull_request

jobs:
  unit-test:
    name: Unit Testing
    runs-on: ubuntu-latest
    container:
      image: atk4/image:latest # https://github.com/atk4/image
    strategy:
      matrix:
        php: ['7.2', '7.3']
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          DB_DATABASE: db
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
      behat:
        image: docksal/behat
        volumes:
          - .:/src
        # Run a built-in web server for access to HTML reports
        ports:
          - 4444:4444
      # Selenium
      browser:
        image: selenium/standalone-chrome
    steps:
      - uses: actions/checkout@v1

      - name: Install simplexml
        run: apt-get install php-xml

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Start PHP BuiltIn Server
        run: php -S 127.0.0.1:8000 > /dev/null 2>&1 &

      - name: Setup coverage folder
        run: mkdir -p coverage

      - name: Setup build folder
        run: mkdir -p build

      - name: Unit Testing
        run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - name: Run behat test
        run: docker exec behat vendor\bin\behat

      - name: Merge coverage logs
        run: vendor/bin/phpcov merge build/logs/ --clover build/logs/cc.xml;

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: build/logs/cc.xml
