name: Unit Testing

on:
  pull_request

jobs:
  unit-test:
    name: Unit Testing
    runs-on: ubuntu-latest
    container:
      image: atk4/image:latest # https://github.com/atk4/image
    strategy:
      matrix:
        php: ['7.2', '7.3']
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          DB_DATABASE: db
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: install docker-compose
        run: curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-Linux-x86_64" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Start DockerCompose
        run: docker-compose -f docker-compose.yml -d

      - name: Check running containers
        run: docker ps -a

      - name: Check logs
        run: |
          docker logs behat
          docker logs web

      - name: Setup composer
        run: composer install

      - name: Install dependencies and SQL
        run: |
          #mysql -uroot -ppassword -h mysql -e 'CREATE DATABASE atk4;'
          #mysql -uroot -ppassword -h mysql atk4 < demos/atk4.sql
          #mv demos/db.github.php demos/db.php

      - name: Setup coverage / build folders
        run: |
          mkdir -p coverage
          mkdir -p build

      - name: Unit Testing
        run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - name: Run behat test
        run: docker exec behat vendor\bin\behat

      - name: Merge coverage logs
        run: vendor/bin/phpcov merge build/logs/ --clover build/logs/cc.xml;

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: build/logs/cc.xml
