name: Unit Testing

on:
  pull_request

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-18.04]
        php: [ '7.2', '7.3', '7.4' ]
    name: PHP ${{ matrix.php }}
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          DB_DATABASE: db
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
      behat:
        image: docksal/behat
        volumes:
          - .:/src
        # Run a built-in web server for access to HTML reports
        ports:
          - 4444:4444
      # Selenium
      browser:
        image: selenium/standalone-chrome
    steps:
      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}
      - name: Start PHP BuiltIn Server
        run: php -S 127.0.0.1:8000 > /dev/null 2>&1 &

      - name: Setup coverage folder
        run: mkdir -p coverage

      - name: Setup build folder
        run: mkdir -p build

      - uses: actions/checkout@v1

      - name: Composer Action
        uses: MilesChou/composer-action@v1.0.1
        with:
          args: install

      - name: PHPUnit testing
        uses: docker://php:5.5
        with:
          args: php vendor/bin/phpunit

      - name: Run behat test
        run: docker exec behat vendor\bin\behat

      - name: Merge coverage logs
        run: vendor/bin/phpcov merge build/logs/ --clover build/logs/cc.xml;

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: build/logs/cc.xml
